// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RecipeSite.Models;
using System;

namespace RecipeSite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191112005402_Initial_AR2")]
    partial class Initial_AR2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RecipeSite.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EquipmentName");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("RecipeSite.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IngredientName");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RecipeSite.Models.RecipeItem", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("EquipmentId");

                    b.Property<int?>("IngredientId");

                    b.Property<string>("Instructions");

                    b.Property<string>("RecipeName");

                    b.Property<int?>("ReviewId");

                    b.Property<int>("ServingSize");

                    b.HasKey("RecipeId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ReviewId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeSite.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Rating");

                    b.Property<string>("ReviewText");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RecipeSite.Models.RecipeItem", b =>
                {
                    b.HasOne("RecipeSite.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId");

                    b.HasOne("RecipeSite.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId");

                    b.HasOne("RecipeSite.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId");
                });
#pragma warning restore 612, 618
        }
    }
}
